"""initial schema

Revision ID: 34fc1fc4d761
Revises: 
Create Date: 2026-09-23 12:06:37.870837

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34fc1fc4d761'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('icon_name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('ruang_publik',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('kategori_id', sa.String(length=50), nullable=True),
    sa.Column('wilayah', sa.String(length=100), nullable=True),
    sa.Column('alamat', sa.Text(), nullable=True),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=8), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=11, scale=8), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('jam_operasional', sa.String(length=255), nullable=True),
    sa.Column('tiket_masuk', sa.String(length=255), nullable=True),
    sa.Column('akses_disabilitas', sa.String(length=255), nullable=True),
    sa.Column('ramah_hewan', sa.String(length=255), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('status_general', sa.String(length=50), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['kategori_id'], ['categories.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fasilitas',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('ruang_publik_id', sa.String(length=50), nullable=False),
    sa.Column('nama', sa.String(length=255), nullable=False),
    sa.Column('kategori', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('lokasi_spesifik', sa.String(length=255), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ruang_publik_id'], ['ruang_publik.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laporan',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('ruang_publik_id', sa.String(length=50), nullable=False),
    sa.Column('fasilitas_id', sa.String(length=50), nullable=True),
    sa.Column('jenis_masalah', sa.String(length=100), nullable=True),
    sa.Column('deskripsi', sa.Text(), nullable=False),
    sa.Column('mode_identitas', sa.String(length=50), nullable=True),
    sa.Column('nama_pelapor', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('foto_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fasilitas_id'], ['fasilitas.id'], ),
    sa.ForeignKeyConstraint(['ruang_publik_id'], ['ruang_publik.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('laporan_timeline',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('laporan_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laporan_id'], ['laporan.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('laporan_timeline')
    op.drop_table('laporan')
    op.drop_table('fasilitas')
    op.drop_table('ruang_publik')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('categories')
    # ### end Alembic commands ###
