"""tambah kolom lokasi laporan

Revision ID: 37c407708e27
Revises: tambah_tabel_etl_run
Create Date: 2026-10-05 19:08:06.743392

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c407708e27'
down_revision: Union[str, None] = 'tambah_tabel_etl_run'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laporan', sa.Column('lat_user', sa.Float(), nullable=True))
    op.add_column('laporan', sa.Column('long_user', sa.Float(), nullable=True))
    op.add_column('laporan', sa.Column('lat_exif', sa.Float(), nullable=True))
    op.add_column('laporan', sa.Column('long_exif', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laporan', 'long_exif')
    op.drop_column('laporan', 'lat_exif')
    op.drop_column('laporan', 'long_user')
    op.drop_column('laporan', 'lat_user')
    # ### end Alembic commands ###
