"""tambah_kolom_jarak_laporan

Revision ID: 74d05cd21291
Revises: tambah_tabel_ruang_publik_foto
Create Date: 2026-10-06 11:45:29.735378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74d05cd21291'
down_revision: Union[str, None] = 'tambah_tabel_ruang_publik_foto'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('laporan', sa.Column('jarak_browser_rp', sa.Float(), nullable=True))
    op.add_column('laporan', sa.Column('jarak_exif_rp', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('laporan', 'jarak_exif_rp')
    op.drop_column('laporan', 'jarak_browser_rp')
    # ### end Alembic commands ###
