"""tambah_tabel_laporan_flag

Revision ID: fe1d83da4fca
Revises: 3996fdaf0f5f
Create Date: 2026-10-08 09:20:32.577913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe1d83da4fca'
down_revision: Union[str, None] = '3996fdaf0f5f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laporan_flag',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('laporan_id', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['laporan_id'], ['laporan.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('laporan_id', 'user_id', name='uq_laporan_flag_pengguna')
    )
    op.create_index(op.f('ix_laporan_flag_laporan_id'), 'laporan_flag', ['laporan_id'], unique=False)
    op.create_index(op.f('ix_laporan_flag_user_id'), 'laporan_flag', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_laporan_flag_user_id'), table_name='laporan_flag')
    op.drop_index(op.f('ix_laporan_flag_laporan_id'), table_name='laporan_flag')
    op.drop_table('laporan_flag')
    # ### end Alembic commands ###
